### ISSUE TITLE
Error checking seal status: Get /v1/sys/seal-status: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by rickpeters** [sjourdan/docker-vault#1]
Hi,
I started vault as a development container and then to test it I perform a docker exec to start a shell in the running container. I only get the message in the issue title. I also tried this by starting a new container form the same image and the setting my `VAULT_ADDR` to the address of the container with the vault development instance but this also does not work.
Do you have any idea what's causing this?
Due to several (corporate :-( ) reasons I am still running on docker 1.3.1 could this be the reason?

**Comment by sjourdan** [comment]
Hi, maybe you get this message because you're somehow talking directly to Vault from your workstation while the dev mode listens only to localhost (so it will work from the container)

Concerning the shell issue: here's how I launch a shell in a running vault container, I don't know if it's similar to how you're doing it: 

```bash
$ docker exec -t -i vault /bin/sh
/ # hostname
vault
/ # vault unseal
Key (will be hidden):
Sealed: false
Key Shares: 1
Key Threshold: 1
Unseal Progress: 0
/ #
```

if you want to try Vault more "realistically", you can try with the demo Consul backend as in the Readme

Does it help ?

**Comment by naxhh** [comment]
It helps. was exactly my problem. You can't test the dev version from outside the container so a docker exec is a must in that case.
